project:
  type: website
  output-dir: docs
  
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
      - section: "Acquire Data"
        contents:
          - military-sites-from-osm.qmd
      - section: "Landsat"
        contents:
          - calculating-lst-and-nvdi.qmd
          - mask-clouds.qmd
          - lst-by-building.qmd
          - overlapping-sites.qmd
          - site-lst-ratio.qmd
      - section: "OS API"
        contents:
          - os-api.qmd
          - os-building-height.qmd
          - os-api-mil-sites.qmd
      - section: "Post GIS"
        contents:
          - postgis-bbox-query.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


