project:
  type: website
  output-dir: docs
  
website:
  title: Seven
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Acquire"
        file: acquire.qmd
      - text: "Exploit"
        file: exploit.qmd
        
  sidebar:
      - title: "Acquire"
        style: "floating"
        search: true
        contents:
        - text: "Acquire"
          href:   acquire.qmd
        - section: "Basics"
          contents:
           - postgis-bbox-query.qmd
           - geocode-mil-sites-from-wiki.qmd
        - section: "OpenStreetMap"
          contents:
           - military-sites-from-osm.qmd
           - military-site-from-osm-bbox.qmd
           - process-osm-data.qmd
        - section: "Ordnance Survey"
          contents:         
            - os-api.qmd
            - os-building-height.qmd
            - os-api-mil-sites.qmd
            - os-download-buildings.qmd
        - section: "Landsat"
          contents:
           - landsat-api.qmd
           - calculating-lst-and-nvdi.qmd
           - mask-clouds.qmd
           - lst-by-building.qmd
           - site-lst-ratio.qmd
      
      - title: "Exploit"
        contents:
        - exploit.qmd
        - primary-site-analysis.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: true


