project:
  type: website
  output-dir: docs
  
website:
  title: Seven
  navbar:
    background: primary
    search: true
    left:
      - text: "Acquire"
        file: acquire.qmd
      - text: "Exploit"
        file: exploit.qmd
        
  sidebar:
      - title: "Acquire"
        style: "floating"
        search: true
        contents:
        - text: "Acquire"
          href:   acquire.qmd
        - section: "Web Scraping"
          contents:
           - geocode-mil-sites-from-wiki.qmd
        - section: "OpenStreetMap"
          contents:
           - military-sites-from-osm.qmd
           - military-site-from-osm-bbox.qmd
           - process-osm-data.qmd
        - section: "Ordnance Survey"
          contents:         
            - os-api.qmd
            - os-building-height.qmd
            - os-download-buildings.qmd
            - os-api-mil-sites.qmd
        - section: "Landsat"
          contents:
           - landsat-api.qmd
           - download-landsat-primary-sites.qmd
        - section: "PostGIS"
          contents: 
           - postgis-bbox-query.qmd
           - raster-from-postgis.qmd
      - title: "Exploit"
        contents:
        - exploit.qmd

        - section: "Landsat"
          contents:
          - calculate-store-nvdi.qmd
          - cloud-cover-multisite.qmd
          - calculating-lst-and-nvdi.qmd
          - mask-clouds.qmd
          - lst-by-building.qmd
          - site-lst-ratio.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: true


