project:
  type: website
  output-dir: docs
  
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - calculating-lst-and-nvdi.qmd
          - mask-clouds.qmd
          - postgis-bbox-query.qmd
          - lst-by-building.qmd
          - overlapping-sites.qmd
          - site-lst-ratio.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


