---
title: Overlaping Sites
---

```{r, warning = FALSE, message = FALSE}
library(sf)
library(igraph)
library(leaflet)
source("R/postgis.R")
```

```{r}
db <- connect_postgres()
DBI::dbListTables(db)

sites <- st_read(db, "mil_boundaries_osm") |>
  dplyr::select(osm_id, name, aeroway, description, landuse, military)

DBI::dbDisconnect(db)


```

```{r}
g <-st_intersects(sites) |>
  graph_from_adj_list()
comp <- components(g)
sites$cluster <- comp$membership

sites_clustered <- sites |> 
  dplyr::group_by(cluster) |>
  dplyr::summarise(geometry = st_union(geometry)) 


```

```{r}
# Add label to site based on largest area
sites$area <- st_area(sites)
site_meta <- sites |>
  dplyr::group_by(cluster) |>
  dplyr::filter(area == max(area)) |>
  as.data.frame() |>
  dplyr::select(name, landuse, military, cluster) |>
  dplyr::distinct()

purrr::imap_dfr(
  site_meta, ~data.frame(
    label = .y, 
    sum_na = sum(is.na(.x)), 
    per_missing = round(100*sum(is.na(.x))/length(.x))
  )
)

sites_clustered <- sites_clustered |>
  dplyr::arrange(cluster) |>
  dplyr::left_join(site_meta, by = "cluster") |>
  dplyr::mutate(csize = comp$csize) |>
  dplyr::select(cluster, csize, primary_name = name, primary_landuse = landuse, primary_military = military, geometry)

sites_clustered$area <- st_area(sites_clustered)


```

```{r}
leaflet(sites_clustered) |>
  addTiles() |>
  setView(0,52, 8) |>
  addPolygons(
    label = ~primary_name, weight = 0, fillColor = "red",  
    popup = ~paste(
      cluster, csize, primary_name, 
      primary_landuse, primary_military, 
      round(area),
      sep = "<br>"
    )
  )

```

```{r}
db <- connect_postgres()
st_write(sites_clustered, db, "mil_bound_clust_osm")
DBI::dbDisconnect(db)
```
